buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath libs.plugins.kotlin
        classpath libs.plugins.gradle
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.5.0"
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}

detekt {
    version = "1.5.0"
    autoCorrect = true
    failFast = false
    config = files("$rootDir/tools/detekt.yml")
    input = files(rootProject.projectDir)

    reports {
        html {
            enabled = true
            destination = file("$rootDir/build/reports/detekt/report.html")
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
