plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
    id 'kotlin-kapt'
}

android {
    compileSdkVersion libs.versions.target_sdk.get().toInteger()
    buildToolsVersion libs.versions.build_tools.get()

    defaultConfig {
        applicationId "com.hako.friendlists"
        minSdkVersion libs.versions.min_sdk.get().toInteger()
        targetSdkVersion libs.versions.target_sdk.get().toInteger()
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "BASE_ENDPOINT", '"https://jsonplaceholder.typicode.com/"'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            debuggable true
            signingConfig signingConfigs.debug
        }
        release {
            debuggable false
            minifyEnabled true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation project(":base")
    implementation project(":userlist")
    implementation project(":albumlist")
    implementation project(":photolist")
}
