apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion libs.versions.target_sdk.get().toInteger()
    buildToolsVersion libs.versions.build_tools.get()

    defaultConfig {
        minSdkVersion libs.versions.min_sdk.get().toInteger()
        targetSdkVersion libs.versions.target_sdk.get().toInteger()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    kapt libs.room.compiler
    api libs.kotlin.std_lib
    api libs.androidx.appcompat
    api libs.androidx.core_ktx
    api libs.androidx.constraint_layout
    api libs.androidx.lifecycle_ext
    api libs.androidx.lifecycle_viewmodel
    api libs.androidx.recycler_view
    api libs.androidx.navigation_fragment
    api libs.androidx.navigation_ui
    api libs.retrofit.runtime
    api libs.retrofit.gson
    api libs.retrofit.rx
    api libs.room.runtime
    api libs.koin.core
    api libs.koin.scope
    api libs.koin.viewmodel
    api libs.rx.core
    api libs.rx.android
    api libs.okhttp_logging_interceptor
    api libs.timber
    api libs.lottie
    api libs.picasso
    testImplementation project(':testing')
    androidTestImplementation project(':testing')
}
