apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    kapt libs.room.compiler
    api libs.kotlin.stdlib
    api libs.androidx.appcompat
    api libs.androidx.core.ktx
    api libs.androidx.constraintlayout
    api libs.androidx.lifecycle.extensions
    api libs.androidx.lifecycle.viewmodel
    api libs.androidx.recyclerview
    api libs.androidx.navigation.fragment
    api libs.androidx.navigation.ui
    api libs.retrofit.runtime
    api libs.retrofit.gson
    api libs.retrofit.rxjava
    api libs.room.runtime
    api libs.koin.core
    api libs.koin.scope
    api libs.koin.viewmodel
    api libs.rxjava.core
    api libs.rxjava.android
    api libs.okhttp.logging.interceptor
    api libs.timber
    api libs.lottie
    api libs.picasso
    testImplementation project(':testing')
    androidTestImplementation project(':testing')
}
