apply plugin: 'com.android.library'

android {
    defaultConfig {
        buildConfigField "String", "DB_NAME", '"userlist.db"'
    }
}

apply from: '../core.gradle'

dependencies {
    implementation project(':base')
    testImplementation project(':testing')
    androidTestImplementation project(':testing')
}
